[package]
name = "hello-world"
description = """
The simplest possible Rust binary, no deps of any kind
"""
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.test-crate]
env = []
